### PR TITLE
Adding `platform` flag to README.md under `arch`

### PR DESCRIPTION
**Pull request by benjibee**

### CODE REVIEW

**Comment by zeke** [comment]
@benjibee do you know of a case where specifying this option is necessary?

**Comment by benjibee** [comment]
@zeke from my understanding, this is the only way I could download `win32` and `darwin` builds for 32-bit and 64-bit architectures manually, as I need to specify `--unsafe-perm` flag.

I had a tough time finding the correct flag after guessing `--os` until I came across the `--platform` flag in some code. But perhaps this would apply to a very small number of users!

**Comment by benjibee** [comment]
Hey @zeke, do I need to close this for it to be merged? I haven't made many pull requests before.

**Comment by zeke** [comment]
> do I need to close this for it to be merged?

nope, you're all set. I just wanted another set of eyes on it before we merge it :)

**Comment by zeke** [comment]
See https://github.com/electron/electron/pull/10225

**Pull request closed without merging**
