### PR TITLE
add electron.d.ts for built-in TypeScript support

### PR DESCRIPTION
**Pull request by zeke**
### The Gist

The Electron project will soon begin publishing a TypeScript declaration file `electron.d.ts` with every release: https://github.com/electron/electron/pull/7857

Many existing third-party `.d.ts` files are published to registries such as [DefinitelyTyped] and [typings], but this is not the ideal approach for publishing, as it requires TypeScript users to manually seek out and install the definitions, and keep them up to date as well.

Because we own the publishing process for the `electron` npm package, we can do our TypeScript users a favor by bundling the file with the package.

To make the Typescript definitions work "out of the box" for users of the `electron` npm package, this PR bundles in that new file and adds a reference to it in `package.json`, per the [typescript guide] recommendations.

### Keeping it Fresh

Once these updates have landed in the `electron-prebuilt` codebase, the tenative plan is to update the [electron-prebuilt-updater] service to bundle the `electron.d.ts` file with every new release.

### Players

cc @marshallofsound, who has been doing all the work to prepare this `electron.d.ts` file.
cc @mafintosh and @kevinsawicki, who help maintain this repo.
cc @joshaber, Electron and TypeScript user who might have input.
cc @miniak, Electron and TypeScript definition maintainer who might also have input.

### Feedback

If anyone has issues with this approach, please chime in. If you find problems in the actual output, please report an issue on one of these repositories:

- [electron/electron](https://github.com/electron/electron) is where the source markdown docs live.
- [electron/electron-docs-linter](https://github.com/electron/electron-docs-linter) parses Electron's docs into structured data
- [MarshallOfSound/Electron-DefinitelyTyped](https://github.com/MarshallOfSound/Electron-DefinitelyTyped) converts structured docs data into an `electron.d.ts` file.

[DefinitelyTyped]: https://github.com/DefinitelyTyped/DefinitelyTyped
[typings]: https://github.com/typings
[typescript guide]: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
[electron-prebuilt-updater]: https://github.com/electron/electron-prebuilt-updater

### CODE REVIEW

**Comment by zeke** [comment]
If anyone wants to try this out:

```
npm i -D https://github.com/electron-userland/electron-prebuilt#33435e1e40c19143bdb828118105cd004b371b06
```

**Comment by unindented** [comment]
@zeke what's the status on this?

**Comment by zeke** [comment]
> what's the status on this?

@MarshallOfSound and I are planning to work on this soon to push it over the finish line. I will be sure to post here as we make progress.

**Comment by zeke** [comment]
Updated `electron.d.ts`. To try it out:

```
npm i -D https://github.com/electron-userland/electron-prebuilt#907e7eb9a81b4e7869b889d6be7e7bc21750ae6c
```

**Comment by zeke** [comment]
https://github.com/electron/electron/pull/7857 has landed in master and the next release of Electron will upload an `electron.d.ts` file as a release asset.

To bootstrap the process of including this file into the `electron` npm package, I'm manually adding it with this pull request. As new versions of Electron are released, this file will be updated automatically by the [electron-prebuilt-updater](https://github.com/electron/electron-prebuilt-updater) webservice.

**Pull request merged**
