### PR TITLE
Adding `unsafe-perm flag` tip to README.md

### PR DESCRIPTION
**Pull request by benjibee**

### CODE REVIEW

**Comment by benjibee** [comment]
Also suggested by @arnonuem in #213

**Comment by benjibee** [comment]
Also mentioned by @a1626 in #263

**Comment by zeke** [comment]
Thanks, @benjibee 

Can you make `unsafe-perm` a link to https://docs.npmjs.com/misc/config#unsafe-perm so folks can easily find out what it's for?

**Comment by benjibee** [comment]
@zeke Updated! ✅

**Comment by zeke** [comment]
See https://github.com/electron/electron/pull/10225

**Pull request closed without merging**
